const state = () => ({
   maplist:[
    {
        name:"日本",
        addr:"japan",
        course:[{
            id:'TJgdLiLF',
            star:4,
            label:['五星住宿','住市区','翻译随行'],
            img_src:'/img/course3.jpeg',
            title:"<日本东京4-8日自由行>可选富士山等一日游，和服租赁体验，可加购接送机，深耕当地热门商圈直采酒店，旅之棲/华盛顿/王子/格拉斯丽/银座国际",
            p_num:"50",
            p_all_num:"50",
            price:"4500"
        },{
            id:'qCwtKAuf',
            star:4,
            label:['五星住宿','住市区','翻译随行'],
            img_src:"/img/course1.jpeg",
            title:"<日本大阪5晚6日自由行>宿核心商圈酒店，逸之彩+微笑+萨拉萨酒店，指定和服体验套餐299元买一送一，品神户牛肉逛环球影城，邂逅禅意京都",
            p_num:"49",
            p_all_num:"50",
            price:"4500"
        },{
            id:'iWcfK2C6',
            star:4,
            label:['五星住宿','住市区','翻译随行'],
            img_src:"/img/course2.jpeg",
            title:"<日本东京-大阪-箱根6日游>大阪进东京出,不走回头路,京都/奈良双古都,亲近萌鹿,春日大社祈福,1晚温泉酒店,含北京/廊坊/唐山至天津机场往返大巴",
            p_num:"66",
            p_all_num:"66",
            price:"4500"
        },{
            id:'wiskeu73',
            img_src:"/img/course4.jpeg",
            title:"<日本大阪-京都-箱根-东京6或7日游>1晚温泉/东京连住享自由/拒签全退/保拼房/双古都/赠wifi/A东进阪出/BC早去晚归,京都奈良镰仓/C含YITI雪乐园",
            p_num:"49",
            p_all_num:"50",
            price:"5500"
        },{
            id:'swed4321',
            img_src:"/img/course1.jpeg",
            title:"札幌市区酒店连住，东武/ANA/格拉斯丽/京王广场品牌酒店，推荐洞爷湖/美瑛青池或者旭山动物园一日游，Rera奥莱人气之旅",
            p_num:"49",
            p_all_num:"50",
            price:"4500"
        }]
    },{
        name:"冰岛",
        addr:"iceland",
        course:[{
            id:'sedrf56y',
            img_src:'/img/course5.jpeg',
            title:"冰岛10日 【4-7人小团 华人导游】 极地探索·特色酒店+熔岩火山+黑沙滩+极光+冰川+精灵马+苔原+温泉——世界尽头的冰与火之歌",
            p_num:"50",
            p_all_num:"50",
            price:"4500"
        },{ 
            id:'e4r56yhb',
            img_src:"/img/course6.jpeg",
            title:"<冰岛四晚+塔林13日游>邂逅极光/四至五星酒店冰岛当地酒店/游轮双人海景舱/蓝湖温泉/草帽山/黑沙滩/斯奈山半岛",
            p_num:"49",
            p_all_num:"50",
            price:"4500"
        },{
            id:'ftgyhc43',
            img_src:"/img/course7.jpeg",
            title:"2-6人专车私导·芬兰+冰岛12天【全球限量·北极圈玻璃屋+蓝湖温泉】 专业向导带领，冰川徒步+雪地摩托车+驯鹿雪橇+极地列车+深入火山内部探险+出海观鲸，一生一次极地之约",
            p_num:"66",
            p_all_num:"66",
            price:"4500"
        },{
            id:'dcvb654r',
            img_src:"/img/course8.jpeg",
            title:"<冰岛+北欧四国11日游>全含，狩猎极光，冰川徒步，蓝湖美浴，黑滩白浪，水晶宫，黄金圈，冰季美瀑，集市尝鲜，升级1晚五星，海鲜自助/三文鱼餐",
            p_num:"49",
            p_all_num:"50",
            price:"5500"
        },]
    },{
        name:"西班牙", 
        addr:"spain",
        course:[{
            id:'der4532w',
            img_src:'/img/spain1.jpeg',
            title:"<西班牙12日游>自营全含无购物，超6400人出游，含欧铁AVE，4到5星住宿，高迪建筑，球场入内，八菜一汤，特色餐，WIFI，拒签无忧 ",
            p_num:"50",
            p_all_num:"50",
            price:"4500"
        },{
            id:'vfredsz2',
            img_src:"/img/spain2.jpeg",
            title:"<西班牙13日游>国航直飞联运，0购物0自费20顿正餐全含，6大入内官导，龙达/米哈斯/波尔图/托莱多，弗拉明戈，皇马餐厅",
            p_num:"49",
            p_all_num:"50",
            price:"4500"
        },{
            id:'prkeindw',
            img_src:"/img/spain3.jpeg",
            title:"<西班牙11-13日游>30人团，部分国航直飞联运，四星酒店，皇宫，圣家族，部分AVE/皇宫/斗牛庄园/海鲜自助/自由活动",
            p_num:"66",
            p_all_num:"66",
            price:"4500"
        },{
            id:'ws3217yg',
            img_src:"/img/spain4.jpeg",
            title:"<欧洲西班牙+葡萄牙13-14日游>会员日每满5000减150,全含4/5星0购物0自费,欧铁AVE,8大景点官导,弗拉明戈,3顿特色餐,酒庄品酒,WIFI",
            p_num:"49",
            p_all_num:"50",
            price:"5500"
        },]
    },{
        name:"埃及", 
        addr:"egypt",
        course:[{
            id:'fpot83ju',
            img_src:'/img/eg1.jpeg',
            title:"<埃及游轮10日游>纯玩0购物，埃航直飞，A线含2段内飞，B线含1段内飞，3晚尼罗河游轮，2晚红海度假酒店，卢克索神庙，卡尔纳克神庙，亚历山大",
            p_num:"50",
            p_all_num:"50",
            price:"10000"
        },{
            id:'deiuwnde',
            img_src:"/img/eg2.jpeg",
            title:"<埃及10日游>三晚尼罗河游船，风帆船或摩托艇，吉萨金字塔群，卢克索，红海，帝王谷入内，一段内陆航班减少拉车，全程五星住宿",
            p_num:"49",
            p_all_num:"50",
            price:"4500"
        },{
            id:'desw34ki',
            img_src:"/img/eg3.jpeg",
            title:"<埃及游轮10-11日游>埃航直飞,全程含餐,内陆双飞省19小时,尼罗河3晚5星游轮,含阿布辛贝+帝王谷,神庙入内含讲解,红海度假,精选导游,3年内大巴 ",
            p_num:"66",
            p_all_num:"66",
            price:"22000"
        },{
            id:'cuejIOLP',
            img_src:"/img/eg4.jpeg",
            title:"<埃及游轮10-11日游>纯玩0购物/含阿布辛贝帝王谷/国五住宿/五星游轮/红海度假/内陆飞+欧洲风情火车/送签证/七大神庙/送上网卡/直飞 ",
            p_num:"49",
            p_all_num:"50",
            price:"5500"
        },]
    },{
        name:"瑞士",
        addr:"swiss",
        course:[{
            id:'DE903JU2',
            img_src:'/img/swiss1.jpeg',
            title:"<瑞士+意大利13日游>自营欧洲，全含0自费，超20000人出游，4到5星，1晚庄园酒店，少女峰，景观列车，五渔村，八菜，WiFi，拒签无忧 ",
            p_num:"50",
            p_all_num:"50",
            price:"4500"
        },{
            id:'SWUI9837',
            img_src:"/img/swiss2.jpeg",
            title:"<德法瑞意11-13日游>纯玩0自费，双宫双船，欧洲雪山，金山列车，五渔村，WIFI，4月起部分罗马深度游T骨牛排/巴黎塞纳河四星 ",
            p_num:"49",
            p_all_num:"50",
            price:"4500"
        },{
            id:'WMEIU833',
            img_src:"/img/swiss3.jpeg",
            title:"<国航直飞-德法瑞意12-14日游>全程含餐+欧洲纯玩+0购物0自费+罗马深度+金色山口+比萨+皮拉图斯+双宫含讲解+双游船+日内瓦湖+慕尼黑+特色餐+WIFI ",
            p_num:"66",
            p_all_num:"66",
            price:"4500"
        },{
            id:'FJRIUKI3',
            img_src:"/img/swiss4.jpeg",
            title:"<瑞士一地深度10-12日游>30人内小团，国航直飞可联运，全程四星，部分升级五星达沃斯洲际，金色山口，三大雪山，莱茵瀑布，特色美食",
            p_num:"49",
            p_all_num:"50",
            price:"5500"
        },]
    },{
        name:"加拿大",
        addr:"canada",
        course:[{
            id:'OLPEUL7b',
            img_src:'/img/cana1.jpeg',
            title:"<加拿大东西海岸7晚9日游>自营,加航直飞,20人小团,东部三城,温哥华3晚连住,TIM HORTONS咖啡,COWS冰激凌,大瀑布,4D电影,卡皮拉诺吊桥,奥莱",
            p_num:"50",
            p_all_num:"50",
            price:"4500"
        },{
            id:'denuwilo',
            img_src:"/img/cana2.jpeg",
            title:"意大利+瑞士+摩纳哥+法国8日游 巴黎集散、水城威尼斯、醉美五渔村、米兰大教堂、斜塔、斗兽场（当地参团）(当地参团)",
            p_num:"49",
            p_all_num:"50",
            price:"4500"
        },{
            id:'deIswe23',
            img_src:"/img/cana3.jpeg",
            title:"<美国+加拿大+黄石+大瀑布20日游>自营,预售减1000/人,2入黄石,保证住西门,5大国家公园,羚羊峡谷,两大公路,加东深度,汤普朗山,千岛湖,海鲜餐 ",
            p_num:"66",
            p_all_num:"66",
            price:"4500"
        },{
            id:'XDRwer34',
            img_src:"/img/cana4.jpeg",
            title:"<美国东西海岸+黄石公园+夏威夷+加拿大22-25日游>爸妈安心游，全国联运送住宿，专业领队/导游2人服务，黄石2次入园，25天8大公园，海鲜餐，保证拼房",
            p_num:"49",
            p_all_num:"50",
            price:"5500"
        },]
    },
    {
        name:"泰国",
        addr:"thailand",
        course:[{
            id:'XDMCIOL3',
            img_src:'/img/thai02.jpeg',
            title:"<泰国曼谷-芭提雅机票+当地5晚6或7日游>万人游纯玩0自费/不外拼假一罚十/全程5星酒店(A线保证1晚国五)/落霞海景餐厅/火车夜市/沙美岛 ",
            p_num:"50",
            p_all_num:"50",
            price:"4500"
        },{
            id:'ASwed123',
            img_src:"/img/thai03.jpeg",
            title:"<泰国普吉岛芭东海滩5晚6或7日自由行>精选芭东人气酒店，泰惠玩五种玩法畅玩普吉，斯米兰出海浮潜，嗨玩海岛",
            p_num:"49",
            p_all_num:"50",
            price:"4500"
        },{
            id:'SED45RFs',
            img_src:"/img/thai04.jpeg",
            title:"<泰国曼谷+芭提雅机票+当地5晚6或7日游>万人之选真纯玩/全程网评五星(商圈,私人沙滩海边,国际五星)/三象神博物馆,暹罗古城,夜市,出海沙美岛/高标泰餐  ",
            p_num:"66",
            p_all_num:"66",
            price:"4500"
        },{
            id:'9sef7GHD',
            img_src:"/img/thai05.jpeg",
            title:"<泰国曼谷-芭提雅机票+当地5晚6日游>轻享纯玩/全程5星酒店/A线出海沙美+火车头夜市+嘟嘟车夜游+万豪海鲜自助/B线出海格兰+水上市场+美功铁道+建兴海鲜 ",
            p_num:"49",
            p_all_num:"50",
            price:"5500"
        },]

    },
    {
        name:"葡萄牙",
        addr:"portugal",
        course:[{
            id:'POI87YCF',
            img_src:'/img/course9.jpeg',
            title:"<欧洲西班牙-葡萄牙12日游>自营，一价全含，超6000人出游，25/30人小团",
            p_num:"50",
            p_all_num:"50",
            price:"4500"
        },{
            id:'eidujwny',
            img_src:"/img/course10.jpeg",
            title:"<欧洲西班牙+葡萄牙13-14日游>全含4/5星0购物0自费,葡萄牙深度3天",
            p_num:"49",
            p_all_num:"50",
            price:"4500"
        },{
            id:'YUDG4rti',
            img_src:"/img/course11.jpeg",
            title:"<希腊+西班牙+葡萄牙15-16日游>部分国航25人团，高迪建筑，阿宫，人骨，WIFI，四月起升1晚5星，双岛2晚悬崖，巴塞直飞圣岛 ",
            p_num:"66",
            p_all_num:"66",
            price:"4500"
        },{
            id:'weSD8963',
            img_src:"/img/course12.jpeg",
            title:"<摩洛哥+西班牙葡萄牙16日游>全含0自费,4至5星,摩洛哥深度,蓝白小镇舍夫沙万,弗拉明戈舞,高迪建筑,酒庄品酒, A含安道尔,B含撒哈拉沙漠",
            p_num:"49",
            p_all_num:"50",
            price:"5500"
        },]
    }
   ]
  })
  
  const mutations = {
    add(state, text) {
        state.list.push(text)
      }
  }
  
  const actions = {
      add:({commit},text) =>{
          commit('add',text)
      }
  }
  
  export default {
      namespaced: true,
      state,
      mutations,
      actions
  }